<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PallaviPP" failures="2" tests="5" name="Testng1" time="7.603" errors="0" timestamp="2022-12-31T21:00:15 IST">
  <testcase classname="testNG.NeostoxTestClass" name="neoStoxLoginValidation" time="7.504"/>
  <testcase classname="testNG.NeoStoxUserIDValidation" name="validateUserName" time="0.002"/>
  <testcase classname="testNG.NeoStoxUserIDValidation" name="ValidatePassword" time="0.007">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.NeoStoxUserIDValidation.ValidatePassword(NeoStoxUserIDValidation.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- ValidatePassword -->
  <testcase classname="testNG.NewTest_Case01" name="TC1" time="0.001"/>
  <testcase classname="testNG.NewTest_Case01" name="TC2" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.NewTest_Case01.TC2(NewTest_Case01.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
</testsuite> <!-- Testng1 -->
